/**
 * TICKET 158-r1 — **THE OS GRAMMAR, IN THE REGISTRY, ONCE.**
 *
 * 158 §2 defines an archetype as a CURRENCY and a TEMPO, and §5.3 is Henry's ruling that the three
 * fields describing them stop living in `collection-v2/collection.json`:
 *
 * > *"move `cur`, `tempo` and `partners` from `collection-v2/collection.json` into the registry
 * > ... so the walker (157), the recruit screen readout (78) and the browser read one source."*
 *
 * Three readers, and before this they read three copies: the browser rendered the design file
 * directly, the walker had nothing to read at all, and the recruit screen showed a firmware id.
 * A design file is a RECORD of what was ruled; it is not a runtime source, and the browser proved
 * that twice over (162d) by silently describing a collection the game no longer shipped.
 *
 * # WHY BOTH THE TOKENS AND THE LINE
 *
 * Henry writes these as prose — `'cards (0e) → Dazed'`, `'zoo (binary Dazed riders) · control
 * (Weakened riders)'` — and the ruling asks for arrays. Both are here, and neither is redundant:
 *
 *   - `currency` / `tempo` are what a MACHINE matches on. 157's walker recruits toward a gym's
 *     counter element and wants to know that kraken_v1 banks `cards` and pays in `Dazed`; a chip
 *     row wants four short words, not a sentence.
 *   - `currencyText` / `tempoText` are what HENRY WROTE, verbatim. The parentheticals are the part
 *     that says WHICH ramp — *"ramp (push piles past 4)"* is a different plan from *"ramp (Str
 *     consume)"* — and dropping them to satisfy a type would be this file editing the design.
 *
 * # PARTNERS ARE FIRMWARE IDS NOW, NOT DISPLAY NAMES
 *
 * The design file says `'Rat v1'`. Nothing can join that to `ratatoskr_v1` by a rule, which is why
 * the readout could not mark "this partner is already in your party" until now. Resolved once, by
 * a hand-written table in `scratch/t158r1_build.py`, and asserted here by `osGrammar.test.ts`.
 *
 * GENERATED by `scratch/t158r1_build.py` from the design file, then owned here. Edit this file;
 * the script is the record of where the values came from, not a build step.
 */

/** 158 §2's four tempos. `keeper` is in the data and was not in §5.3's list — see the write-back. */
export type TempoKind = 'zoo' | 'ramp' | 'control' | 'keeper';

export interface OSPartner {
    /** The firmware id, resolved from the design file's display name. */
    readonly osId: string;
    /** Henry's sentence, verbatim. */
    readonly why: string;
}

export interface OSGrammar {
    /** Atomic currency tokens, in the order Henry wrote them. What the walker matches on. */
    readonly currency: ReadonlyArray<string>;
    /** The designed line, parentheticals and all. What a reader is shown. */
    readonly currencyText: string;
    /** The tempos this OS plays, deduped, in order. */
    readonly tempo: ReadonlyArray<TempoKind>;
    /** The designed line. */
    readonly tempoText: string;
    /** Who feeds it and who reads it — by firmware id, so a party can be checked against it. */
    readonly partners: ReadonlyArray<OSPartner>;
}

/**
 * The EA twelve. An OS absent from this table has no grammar recorded — `grammarFor` returns
 * undefined rather than an empty one, because "no currency" and "nobody has written the currency
 * down" are different answers and the readout says so differently.
 */
export const OS_GRAMMAR: Readonly<Record<string, OSGrammar>> = {
    fenrir_v1: {
        currency: ['Strength', 'HP'],
        currencyText: 'Strength · HP',
        tempo: ['ramp'],
        tempoText: 'ramp (Str consume) · ramp (HP as fuel)',
        partners: [
            { osId: 'skoll_v1', why: 'Howl / TREACHERY put Strength on Fenrir for free' },
            { osId: 'huldra_v1', why: 'Weakens the attackers so the recoil deck survives' },
            { osId: 'ratatoskr_v1', why: 'GOSSIP heals the HP Fenrir spends' },
        ],
    },
    fenrir_v2: {
        currency: ['Burn', 'Sharp'],
        currencyText: 'Burn → Sharp',
        tempo: ['ramp', 'control'],
        tempoText: 'ramp (Burn → Sharp → consume) · control (side Burn)',
        partners: [
            { osId: 'kraken_v2', why: 'Scald / Boiling Surge are Burn — steam feeds CINDER_WALL' },
            { osId: 'skoll_v2', why: 'Every Brand and Ember Jab is a Sharp for Fenrir' },
            { osId: 'huldra_v1', why: 'Bolster’s Sharp lands on Fenrir; Cinder Lance reads it' },
        ],
    },
    skoll_v1: {
        currency: ['Strength'],
        currencyText: 'Strength',
        tempo: ['zoo', 'control'],
        tempoText: 'zoo (Str multi-hit) · control (deny + battery)',
        partners: [
            { osId: 'fenrir_v1', why: 'Howl + UNBOUND_KERNEL: Fenrir’s consume eats Sköll’s Strength' },
            { osId: 'huldra_v1', why: 'Bolster keeps allies alive to be hit; ALLURE turns the buff into Weakened' },
            { osId: 'huldra_v2', why: 'Bark on allies = chip damage that still procs TREACHERY without killing' },
        ],
    },
    skoll_v2: {
        currency: ['Burn'],
        currencyText: 'Burn (detonation)',
        tempo: ['ramp', 'zoo'],
        tempoText: 'ramp (push piles past 4) · zoo (cheap Burn riders)',
        partners: [
            { osId: 'fenrir_v2', why: 'Every Burn Sköll adds is Sharp for Fenrir' },
            { osId: 'kraken_v2', why: 'Steam Burns pre-load the pile Sköll detonates' },
            { osId: 'jormungandr_v2', why: 'Two clocks: Poison and Burn ignore Sharp walls' },
        ],
    },
    ratatoskr_v1: {
        currency: ['cards'],
        currencyText: 'cards (0e casts)',
        tempo: ['zoo', 'keeper'],
        tempoText: 'zoo (cards-played scalar) · keeper (heal + draw)',
        partners: [
            { osId: 'ratatoskr_v2', why: 'Two 0e engines share one pile; INSTIGATOR Dazes what GOSSIP heals through' },
            { osId: 'jormungandr_v1', why: 'Undertow is a 0e cast AND a Water card for OUROBOROS' },
            { osId: 'fenrir_v1', why: 'GOSSIP refunds the HP the berserker spends' },
        ],
    },
    ratatoskr_v2: {
        currency: ['cards', 'Dazed'],
        currencyText: 'cards (0e) → Dazed',
        tempo: ['zoo', 'control'],
        tempoText: 'zoo (binary Dazed riders) · control (Weakened riders)',
        partners: [
            { osId: 'kraken_v1', why: 'Rat makes Dazed by the cast; Crushing Depths consumes it per stack' },
            { osId: 'jormungandr_v2', why: 'Dazed on the target is +power on each of Serpent Flurry’s three hits' },
            { osId: 'huldra_v1', why: 'Rat’s Weakened feeds Sap Strength and Hexbloom' },
        ],
    },
    jormungandr_v1: {
        currency: ['cards'],
        currencyText: 'cards (played)',
        tempo: ['zoo', 'ramp'],
        tempoText: 'zoo (cards-played scalar) · ramp (refunds)',
        partners: [
            { osId: 'kraken_v1', why: 'Both engines eat Undertow; ABYSSAL_INK turns Jorm’s draws into Dazed' },
            { osId: 'ratatoskr_v1', why: '0e Water cards proc GOSSIP too' },
            { osId: 'kraken_v2', why: 'Jorm’s refunds pay for Kraken’s 3e turn' },
        ],
    },
    jormungandr_v2: {
        currency: ['Poison'],
        currencyText: 'Poison',
        tempo: ['zoo', 'ramp'],
        tempoText: 'zoo (Poison riders × multi-hit) · ramp (double, then trigger)',
        partners: [
            { osId: 'huldra_v2', why: 'Thornguard’s conditional Poison is TOXIN_FANG fuel' },
            { osId: 'huldra_v1', why: 'Hexbloom converts Weakened into a pile Jorm reads' },
            { osId: 'ratatoskr_v2', why: 'Dazed on the target adds to every one of the flurry’s hits' },
        ],
    },
    kraken_v1: {
        currency: ['cards', 'Dazed'],
        currencyText: 'cards (drawn) → Dazed',
        tempo: ['zoo', 'control'],
        tempoText: 'zoo (draw scalar) · control (Dazed consume)',
        partners: [
            { osId: 'jormungandr_v1', why: 'Undertow serves both OSes' },
            { osId: 'ratatoskr_v2', why: 'Two Dazed engines, one Crushing Depths' },
            { osId: 'skoll_v1', why: 'Dazed on the target is per-hit power for Flare Burst' },
        ],
    },
    kraken_v2: {
        currency: ['Energy'],
        currencyText: 'Energy',
        tempo: ['ramp', 'control'],
        tempoText: 'ramp (Energized → 3e) · control (steam Burn)',
        partners: [
            { osId: 'fenrir_v2', why: 'Every steam Burn is a Sharp for Fenrir' },
            { osId: 'skoll_v2', why: 'Steam pre-loads the piles Sköll detonates' },
            { osId: 'jormungandr_v1', why: 'Refunds pay for the 3e turn' },
        ],
    },
    huldra_v1: {
        currency: ['Sharp', 'Regen', 'Weakened'],
        currencyText: 'Sharp/Regen (given) → Weakened',
        tempo: ['control', 'keeper'],
        tempoText: 'control (Weakened scalar/consume) · keeper (ally buffs)',
        partners: [
            { osId: 'fenrir_v1', why: 'Weakened cancels enemy Strength stack for stack; Bolster’s Sharp lands where Cinder Lance reads it' },
            { osId: 'skoll_v1', why: 'Weakened cancels enemy Strength stack for stack; Bolster’s Sharp lands where Cinder Lance reads it' },
            { osId: 'jormungandr_v2', why: 'Hexbloom’s Poison is TOXIN_FANG fuel' },
            { osId: 'ratatoskr_v2', why: 'Rat’s Weakened riders feed Sap Strength' },
        ],
    },
    huldra_v2: {
        currency: ['Bark'],
        currencyText: 'Bark',
        tempo: ['ramp', 'control'],
        tempoText: 'ramp (Bark scalar/consume) · control (Bark → Poison, shield allies)',
        partners: [
            { osId: 'jormungandr_v2', why: 'Thornguard’s Poison is TOXIN_FANG fuel' },
            { osId: 'skoll_v1', why: 'Bark on allies keeps TREACHERY’s chip damage survivable' },
            { osId: 'ratatoskr_v1', why: 'A shielded zoo heals AND poisons' },
        ],
    },
};

/** The grammar for `osId`, or undefined when none has been recorded (every post-EA OS). */
export function grammarFor(osId: string): OSGrammar | undefined {
    return OS_GRAMMAR[osId];
}

/**
 * The partners of `osId` that are ALREADY on the field, as firmware ids.
 *
 * The readout's whole job on the recruit screen: a partner hint is advice until it is a fact about
 * the party in front of you. Order follows `partners`, so the strongest-authored hint reads first.
 */
export function partnersInParty(osId: string, partyOS: ReadonlyArray<string>): ReadonlyArray<OSPartner> {
    const held = new Set(partyOS);
    return grammarFor(osId)?.partners.filter((p) => held.has(p.osId)) ?? [];
}
