# Collection v2.1b — the EA twelve under the 158 grammar. Numbers are DRAFTS for the 149c scorer.
# v2.1 (2026-09-23, Henry's review): SLOT TAX — a card also costs the card it displaces, so the bands are
#   0e ≈ 12 · 1e ≈ 30 · 2e ≥ 70 · 3e ≥ 120, and a 2e/3e card must do what two 1e cards cannot (side, multi-hit,
#   consume, state change). ONE-JOB RULE at 0e — no 0e card is another 0e card plus a rider.
# v2.1b (09-23): MULTI-HIT RULE — a multi-hit card carries the band's power split across its hits (1e = 30/hits,
#   2e = 70/hits, 0e = 12/hits); the per-hit status bonus is the scaling, not a discount on the base.
CHANGELOG = [
 ('Draw glue', 'Quick Scan removed; Forage (draw 1, take 15 power) is the generic 0e draw in every kit. Undertow = draw + 1 Weakened on yourself (Legion tested) and stays Water for OUROBOROS.'),
 ('Wording', 'Capacitor and Tidal Battery say Energized. Tidal Battery unchanged otherwise (every ally gains 1 Energized; run card).'),
 ('Fenrir self damage', 'Desperate Strike (8p, +1 Str, −3% HP) and Glass Cannon (45p, −5% HP) join the kit; Fury Strike and Blood Rite move to the run pool.'),
 ('2e / 3e rebands', 'Hydro Blast 120 · Maelstrom 100 + 3 Dazed · Tidal Wave 55 side · Boiling Surge 55 + 2 Burn · Pile On 35, again if Dazed · Crippling Vine is now a SIDE card (20 to each, 2 Weakened each) · Seed Bomb 20/card · Crushing Depths 20/stack · Slander 15/stack · Cinder Lance 40 + 6/Sharp · Sharp Edge 15/stack · Bark Smash 6/point · Venom Glut 15/stack consumed · Blightbloom 30 + 5 Poison · Ink Cloud 25 side · Pack Tactics 15×3 · Wildfire 45 side.'),
 ('1e rebands', 'Surge Protection → 1e, 25p + refund · Venom Fang 30 · Brand 25 · Snap 20/+12 · Slag Strike 22 · Riptide Run 20 · Sap Strength 20 + 6/Weakened.'),
 ('Multi-hit rule', 'A multi-hit card carries the full band split across its hits — Flare Burst 15×2, Pack Tactics 23×3, Serpent Flurry 10×3, Acorn Toss 6×2. Ragnarok Edge +1 power per 1% HP missing (max 50). Flashover 50 + 15/Burn (80 at 2 Burn). Scald 2 Burn + 1 self Dazed. Pile On 45, again if Dazed.'),
 ('0e one-job', 'Ember Jab = the Burn HIT (8p + 1 Burn); Ignite = the Burn CANTRIP (1 Burn, draw if already Burning). Snarl = 2 Weakened on one; Pollen Cloud = 1 Weakened on the side. Acorn Toss = 5p twice (the 0e multi-hit; Scurry removed); Tackle = the flat 12.'),
]

# status: keep = existing card unchanged (id as in programs.json) · revise = existing id, text changed · new
# shape: enabler | scalar | consume | glue | hate (daemon) | converter
# target: Single (enemy) | Self | Side (enemy side) | Ally | AllySide

CARDS = [
# ---------------- GENERICS (None) ----------------
dict(id='tackle', old='water_slap', name='Tackle', cost=0, el='None', cat='Attack', tgt='Single', text='12 power.', shape='glue', cur='—', status='keep'),
dict(id='deep_scan', old='squirrel_away', name='Deep Scan', cost=1, el='None', cat='Skill', tgt='Self', text='Draw 2.', shape='glue', cur='cards', status='keep'),
dict(id='capacitor', name='Capacitor', cost=2, el='None', cat='Skill', tgt='Self', text='Gain 3 Energized.', shape='enabler', cur='Energy', status='keep'),
dict(id='soothe', name='Soothe', cost=0, el='None', cat='Skill', tgt='Ally', text='Remove 1 stack of a debuff from an ally.', shape='glue', cur='—', status='revise', why='Was Nature/Self. Now the generic ally cleanse — the only cheap answer to Poison/Burn piles, so it must be castable by anyone.'),
dict(id='mend', name='Mend', cost=1, el='None', cat='Heal', tgt='Ally', text='Heal an ally with 20 power.', shape='glue', cur='—', status='new', why='The ally-target heal (160-e1). Keeper role for any party.'),
dict(id='overclock_core', name='Overclock Core', cost=2, el='None', cat='Daemon', tgt='Self', text='Daemon (exhaust): Max Energy +1 for the rest of the battle.', shape='enabler', cur='Energy', status='new', why='160-r1. Battery Pack at half price; tempo is the tax.'),
dict(id='short_fuse', name='Short Fuse', cost=2, el='None', cat='Daemon', tgt='Self', text='Daemon (exhaust): an enemy that ends its turn with unspent Energy takes 10 power per point.', shape='hate', cur='Energy', status='new', why='160-r2. The anti-ramp answer, printed with the ramp.'),
# ---------------- DAEMONS (hate + currency) ----------------
dict(id='riptide', name='Riptide', cost=2, el='None', cat='Daemon', tgt='Self', text='Daemon (exhaust): whenever an enemy plays a card, deal 8 power to it.', shape='hate', cur='cards', status='keep'),
dict(id='short_circuit', name='Short Circuit', cost=2, el='None', cat='Daemon', tgt='Self', text='Daemon (exhaust): whenever an enemy draws a card outside its draw phase, deal 15 power to it.', shape='hate', cur='cards', status='keep'),
dict(id='static_ward', name='Static Ward', cost=2, el='None', cat='Daemon', tgt='Self', text='Daemon (exhaust): whenever an enemy applies a status to your side, it takes 8 power.', shape='hate', cur='statuses', status='new', why='Anti-control. Fine against anyone, sharp against Huldra/Kraken-style decks.'),
dict(id='core_overclock', old='core_overclock_daemon', name='Core Overclock', cost=2, el='Fire', cat='Daemon', tgt='Self', text='Daemon (exhaust): +1 power for every 2 Strength you hold.', shape='scalar', cur='Strength', status='keep'),
dict(id='cinder_armor', old='cinder_armor_daemon', name='Cinder Armor', cost=2, el='Fire', cat='Daemon', tgt='Self', text='Daemon (exhaust): cards that add Burn also add 1 Sharp to the host.', shape='converter', cur='Burn', status='keep'),
dict(id='ember_ward', name='Ember Ward', cost=2, el='Fire', cat='Daemon', tgt='Self', text='Daemon (exhaust): whenever an ally is hit by an attack, the attacker gains 1 Burn.', shape='enabler', cur='Burn', status='new', why="Henry's 'when attacked apply Burn' (Fenrir v2 control lane)."),
dict(id='feedback_loop', old='feedback_loop_daemon', name='Feedback Loop', cost=1, el='Water', cat='Daemon', tgt='Self', text='Daemon (exhaust): whenever an effect draws you a card, hit a random enemy for 7 power.', shape='scalar', cur='cards', status='keep'),
dict(id='hoofbeat', old='hoofbeat_daemon', name='Hoofbeat', cost=2, el='None', cat='Daemon', tgt='Self', text='Daemon (exhaust): whenever you play a 0-cost card, deal 8 power to a random enemy.', shape='scalar', cur='cards', status='revise', why='Was Air; generic now so the 0e zoo (Rat) can find it.'),
dict(id='echo_chamber', old='echo_chamber_v2', name='Echo Chamber', cost=2, el='Nature', cat='Daemon', tgt='Self', text='Daemon (exhaust): whenever you play a 0-cost card, generate a 0-cost Feedback token in your hand.', shape='enabler', cur='cards', status='keep'),
dict(id='reactive_plating', name='Reactive Plating', cost=2, el='None', cat='Daemon', tgt='Self', text='Daemon (exhaust): when an ally takes damage from an enemy attack, it gains 1 Sharp. Max 3 per turn.', shape='enabler', cur='Sharp', status='keep'),
dict(id='thermal_overload', name='Thermal Overload', cost=2, el='Fire', cat='Daemon', tgt='Self', text='Daemon (exhaust): your Burns deal 50% more damage. Host takes 5 Fire damage at turn end.', shape='scalar', cur='Burn', status='keep'),
# ---------------- FIRE ----------------
dict(id='ignite', name='Ignite', cost=0, el='Fire', cat='Status', tgt='Single', text='Apply 1 Burn. If the target was already Burning, draw a card.', shape='enabler', cur='Burn', status='revise', why='09-23 one-job rule: Ember Jab is the 0e Burn HIT; Ignite is the 0e Burn CANTRIP on a pile.'),
dict(id='ember_jab', old='fire_poke', name='Ember Jab', cost=0, el='Fire', cat='Attack', tgt='Single', text='8 power. Apply 1 Burn.', shape='enabler', cur='Burn', status='revise', why='Fire Poke was 1e/22. The 0e Burn rider the zoo lanes need.'),
dict(id='brand', name='Brand', cost=1, el='Fire', cat='Attack', tgt='Single', text='25 power. If the target is Burning, apply 1 more Burn.', shape='enabler', cur='Burn', status='new', why='Feeds detonation (Sköll v2) without being an OS reskin.'),
dict(id='fury_strike', name='Fury Strike', cost=1, el='Fire', cat='Attack', tgt='Single', text='25 power. Gain 1 Strength.', shape='enabler', cur='Strength', status='keep'),
dict(id='flare_burst', name='Flare Burst', cost=1, el='Fire', cat='Attack', tgt='Single', text='15 power, twice.', shape='scalar', cur='Strength', status='new', why='The Fire multi-hit. Status power is added PER HIT, so this is the Str scalar (and the Dazed-on-target scalar).'),
dict(id='pack_tactics', name='Pack Tactics', cost=2, el='Fire', cat='Attack', tgt='Single', text='23 power, three times.', shape='scalar', cur='Strength', status='new'),
dict(id='howl', name='Howl', cost=1, el='Fire', cat='Skill', tgt='AllySide', text='Every ally gains 1 Strength.', shape='enabler', cur='Strength', status='new', why="Sköll's battery lane: Str as a PARTY currency (UNBOUND_KERNEL reads allies' attacks)."),
dict(id='snarl', name='Snarl', cost=0, el='Fire', cat='Status', tgt='Single', text='Apply 2 Weakened.', shape='enabler', cur='Weakened', status='new', why="Sköll v1's deny half: keep the chip damage TREACHERY feeds on small."),
dict(id='snap', name='Snap', cost=1, el='Fire', cat='Attack', tgt='Single', text='20 power. +12 power if the target is Weakened.', shape='scalar', cur='Weakened', status='new', why='Sköll v1’s second payoff on a DIFFERENT counter (cleanse, not Weakened) — the §2.6 rule.'),
dict(id='brute_force', name='Brute Force', cost=1, el='Fire', cat='Attack', tgt='Single', text='25 power. +8 power if you have Strength.', shape='scalar', cur='Strength', status='keep'),
dict(id='battle_rhythm', name='Battle Rhythm', cost=1, el='Fire', cat='Attack', tgt='Single', text='25 power. Above half HP: gain 2 Strength. Otherwise gain 2 Sharp.', shape='enabler', cur='Strength', status='keep'),
dict(id='crimson_draw', name='Crimson Draw', cost=1, el='Fire', cat='Attack', tgt='Single', text='18 power. Heal 8.5% of your max HP.', shape='glue', cur='HP', status='keep'),
dict(id='war_pact', name='War Pact', cost=0, el='Fire', cat='Skill', tgt='Self', text='Above half HP: gain 2 Strength and 2 Dazed. Below half: heal with 15 power.', shape='enabler', cur='Strength', status='keep'),
dict(id='unbound_fang', name='Unbound Fang', cost=1, el='Fire', cat='Attack', tgt='Single', text='5 power per stack of Strength you hold, then lose half of them.', shape='consume', cur='Strength', status='keep'),
dict(id='sun_devourer', name='Sun Devourer', cost=2, el='Fire', cat='Attack', tgt='Single', text='Consume all your Strength: 15 power per stack consumed.', shape='consume', cur='Strength', status='keep', why="Moves from Sköll to Fenrir — Fenrir is the Str CONSUME, Sköll is the Str multi-hit."),
dict(id='ragnarok_edge', name='Ragnarok Edge', cost=1, el='Fire', cat='Attack', tgt='Single', text='20 power. +1 power per 1% of your max HP missing (max 50%).', shape='scalar', cur='HP', status='keep'),
dict(id='blood_rite', name='Blood Rite', cost=1, el='Fire', cat='Attack', tgt='Single', text='15 power. +15 power above half HP; otherwise heal with 40 power.', shape='enabler', cur='HP', status='keep'),
dict(id='desperate_strike', name='Desperate Strike', cost=0, el='Fire', cat='Attack', tgt='Single', text='8 power. Gain 1 Strength. Lose 3% of your max HP.', shape='enabler', cur='Strength', status='revise', why='Fenrir needs more self damage (Henry 09-23): the 0e Str enabler pays in HP and feeds Ragnarok Edge.'),
dict(id='glass_cannon', name='Glass Cannon', cost=1, el='Fire', cat='Attack', tgt='Single', text='45 power. Lose 5% of your max HP.', shape='enabler', cur='HP', status='keep', why='Fenrir v1’s berserker lane: over-band damage paid in HP.'),
dict(id='molten_core', name='Molten Core', cost=1, el='Fire', cat='Skill', tgt='Single', text='Apply 4 Burn if you hold Sharp. Otherwise 2 Burn.', shape='enabler', cur='Burn', status='keep'),
dict(id='slag_strike', name='Slag Strike', cost=1, el='Fire', cat='Attack', tgt='Single', text='22 power. Gain 1 Sharp.', shape='enabler', cur='Sharp', status='keep'),
dict(id='cinder_lance', name='Cinder Lance', cost=2, el='Fire', cat='Attack', tgt='Single', text='40 power. +6 power per stack of Sharp you hold.', shape='scalar', cur='Sharp', status='keep'),
dict(id='sharp_edge', name='Sharp Edge', cost=2, el='Fire', cat='Attack', tgt='Single', text='Consume your Sharp: 15 power per stack consumed.', shape='consume', cur='Sharp', status='new', why='The Sharp consume the roster lacks (Fenrir v2 ramp lane).'),
dict(id='inferno', name='Inferno', cost=2, el='Fire', cat='Status', tgt='Side', text='Apply 2 Burn to the enemy side.', shape='enabler', cur='Burn', status='keep'),
dict(id='heat_wave', name='Heat Wave', cost=2, el='Fire', cat='Status', tgt='Side', text="Double the enemy side's Burn stacks.", shape='consume', cur='Burn', status='keep', why='The detonation ramp: past the cap of 4, Burn detonates.'),
dict(id='flashover', name='Flashover', cost=2, el='Fire', cat='Attack', tgt='Single', text='50 power. +15 power per Burn on the target.', shape='scalar', cur='Burn', status='new', why='Burn scalar that reads the TARGET — any ally’s Burn counts.'),
dict(id='wildfire', name='Wildfire', cost=3, el='Fire', cat='Attack', tgt='Side', text='45 power to the enemy side. Apply 1 Burn to each.', shape='enabler', cur='Burn', status='new'),
dict(id='ash_communion', name='Ash Communion', cost=2, el='Fire', cat='Heal', tgt='Self', text='Consume your Burn: heal with 30 power per stack consumed.', shape='consume', cur='Burn', status='keep'),
# ---------------- WATER ----------------
dict(id='undertow', name='Undertow', cost=0, el='Water', cat='Skill', tgt='Self', text='Draw a card. You gain 1 Weakened.', shape='enabler', cur='cards', status='revise', why='Henry 09-23 (Legion tested): the 0e draw carries a drawback.'),
dict(id='blind_spot', name='Blind Spot', cost=0, el='Water', cat='Attack', tgt='Single', text='6 power. Apply 1 Dazed.', shape='enabler', cur='Dazed', status='keep'),
dict(id='whirlpool', old='whirlpool_v2', name='Whirlpool', cost=1, el='Water', cat='Attack', tgt='Single', text='8 power. Draw a card. Apply 2 Dazed.', shape='enabler', cur='Dazed', status='keep'),
dict(id='pressure_point', name='Pressure Point', cost=1, el='Water', cat='Attack', tgt='Single', text='22 power. If the target is Dazed, draw 1.', shape='enabler', cur='cards', status='keep'),
dict(id='ink_stream', name='Ink Stream', cost=1, el='Water', cat='Attack', tgt='Single', text='33 power for each card an effect drew you this turn.', shape='scalar', cur='cards', status='keep', why='KRAKEN ONLY now — it was in both Water decks.'),
dict(id='crushing_depths', name='Crushing Depths', cost=2, el='Water', cat='Attack', tgt='Single', text="Consume all Dazed on the target: 20 power per stack consumed.", shape='consume', cur='Dazed', status='keep'),
dict(id='slander', name='Slander', cost=2, el='Water', cat='Attack', tgt='Single', text='15 power per stack of Dazed on the target.', shape='scalar', cur='Dazed', status='revise', why='Was Nature (Rat). Per-stack Dazed is Kraken’s; Rat keeps the binary "if Dazed" riders.'),
dict(id='ink_cloud', name='Ink Cloud', cost=2, el='Water', cat='Attack', tgt='Side', text='25 power to the enemy side. Apply 2 Dazed to each.', shape='enabler', cur='Dazed', status='keep'),
dict(id='scavenge_data', name='Scavenge Data', cost=1, el='Water', cat='Skill', tgt='Self', text='Draw a Water card.', shape='enabler', cur='cards', status='keep'),
dict(id='serpents_coil', name="Serpent's Coil", cost=1, el='Water', cat='Attack', tgt='Single', text='10 power for every card you played this turn.', shape='scalar', cur='cards', status='keep'),
dict(id='surge_protection', name='Surge Protection', cost=1, el='Water', cat='Attack', tgt='Single', text='25 power. If an effect drew you a card this turn, refund 1 Energy.', shape='glue', cur='Energy', status='revise', why='Henry 09-23: a 25p 1e, not a 2e. 157-r3 re-tags it GLUE, not scalar: 25 power is a flat hit and the refund is a rider on it, so it banks nothing and cashes nothing. The tag matters because the one-payoff rule counts scalars - with this as a scalar, jormungandr_v1 would open on two payoffs.'),
dict(id='riptide_run', name='Riptide Run', cost=1, el='Water', cat='Attack', tgt='Single', text='20 power. Refund 1 Energy if this is the third or later card you played this turn.', shape='enabler', cur='Energy', status='new', why="Jorm v1's refund ramp, the shape nobody else has."),
dict(id='corrosive_leak', name='Corrosive Leak', cost=0, el='Water', cat='Skill', tgt='Self', text='Poison yourself 2 stacks. Gain 1 Energized.', shape='enabler', cur='Energy', status='keep'),
dict(id='tidal_battery', name='Tidal Battery', cost=2, el='Water', cat='Skill', tgt='AllySide', text='Every ally gains 1 Energized.', shape='enabler', cur='Energy', status='revise', why='RUN CARD (Henry 09-22) — never in a kit. Description says Energized (09-23).'),
dict(id='tide_pool', name='Tide Pool', cost=1, el='Water', cat='Skill', tgt='Self', text='Gain 1 Energized. Draw 1.', shape='enabler', cur='Energy', status='new'),
dict(id='corrosive_bolt', name='Corrosive Bolt', cost=1, el='Water', cat='Attack', tgt='Single', text='Apply 3 Poison.', shape='enabler', cur='Poison', status='keep'),
dict(id='venom_fang', name='Venom Fang', cost=1, el='Water', cat='Attack', tgt='Single', text='30 power.', shape='scalar', cur='Poison', status='keep', why='Plain hit that TOXIN_FANG turns into a scalar.'),
dict(id='serpent_flurry', name='Serpent Flurry', cost=1, el='Water', cat='Attack', tgt='Single', text='Three strikes of 10 power.', shape='scalar', cur='Poison', status='keep', why='Multi-hit × per-Poison OS bonus — Jorm v2’s unique thing.'),
dict(id='toxic_surge', name='Toxic Surge', cost=1, el='Water', cat='Skill', tgt='Single', text='Apply 1 Poison, then trigger Poison damage immediately.', shape='consume', cur='Poison', status='keep'),
dict(id='contagion', name='Contagion', cost=2, el='Water', cat='Status', tgt='Single', text="Double the target's Poison stacks.", shape='enabler', cur='Poison', status='keep'),
dict(id='venom_glut', name='Venom Glut', cost=2, el='Water', cat='Attack', tgt='Single', text="Consume the target's Poison: 15 power per stack consumed.", shape='consume', cur='Poison', status='new', why='The Poison consume, reads the TARGET. 15/stack (09-23: 8 was underpowered for what it removes) — after Contagion a 6-pile is 180.'),
dict(id='spreading_rot', name='Spreading Rot', cost=1, el='Water', cat='Status', tgt='Side', text='Apply 2 Poison to the enemy side.', shape='enabler', cur='Poison', status='keep'),
dict(id='scald', name='Scald', cost=0, el='Water', cat='Attack', tgt='Single', text='Apply 2 Burn. You gain 1 Dazed.', shape='enabler', cur='Burn', status='keep'),
dict(id='boiling_surge', name='Boiling Surge', cost=2, el='Water', cat='Attack', tgt='Single', text='55 power. Apply 2 Burn.', shape='scalar', cur='Energy', status='keep', why='A ≥2e Water attack IS the TIDAL_CRUSH scalar; the Burn is the steam lane.'),
dict(id='maelstrom', name='Maelstrom', cost=3, el='Water', cat='Attack', tgt='Single', text='100 power. Apply 3 Dazed.', shape='consume', cur='Energy', status='keep'),
dict(id='hydro_blast', name='Hydro Blast', cost=3, el='Water', cat='Attack', tgt='Single', text='120 power.', shape='consume', cur='Energy', status='keep'),
dict(id='tidal_wave', old='tidal_wave_v2', name='Tidal Wave', cost=3, el='Water', cat='Attack', tgt='Side', text='55 power to the enemy side.', shape='consume', cur='Energy', status='keep'),
# ---------------- NATURE ----------------
dict(id='acorn_toss', old='seed_spit', name='Acorn Toss', cost=0, el='Nature', cat='Attack', tgt='Single', text='6 power, twice.', shape='enabler', cur='cards', status='revise', why='Seed Spit minus the Poison, as the 0e multi-hit: two Dazed-on-target hits for one INSTIGATOR proc. Tackle is the flat 0e.'),
dict(id='forage', name='Forage', cost=0, el='None', cat='Skill', tgt='Self', text='Draw 1. Take damage equal to 15 power.', shape='glue', cur='cards', status='keep', why='Henry 09-23: the 0e draw has a drawback and is generic — Forage is the glue in every kit; Undertow is the Water one and feeds OUROBOROS.'),
dict(id='seed_bomb', old='seed_bomb_v2', name='Seed Bomb', cost=2, el='Nature', cat='Attack', tgt='Single', text='20 power per card you played this turn.', shape='scalar', cur='cards', status='keep'),
dict(id='rejuvenation', name='Rejuvenation', cost=1, el='Nature', cat='Heal', tgt='Self', text='Draw a card. Heal with 25 power.', shape='glue', cur='cards', status='keep'),
dict(id='tend', old='healing_mist', name='Tend', cost=0, el='Nature', cat='Heal', tgt='Ally', text='An ally gains 1 Sharp and heals with 8 power.', shape='enabler', cur='Sharp', status='revise', why='Growth/Healing Mist made ally-target. A buff on an ally = Weakened on an enemy under ALLURE_PROXY.'),
dict(id='bolster', name='Bolster', cost=1, el='Nature', cat='Skill', tgt='Ally', text='An ally gains 3 Sharp.', shape='enabler', cur='Sharp', status='new', why='The keeper card. Read by Cinder Lance / Thorn Whip on whoever holds it.'),
dict(id='verdant_ward', name='Verdant Ward', cost=2, el='Nature', cat='Skill', tgt='AllySide', text='Every ally gains 2 Regen and 1 Sharp.', shape='enabler', cur='Sharp', status='new'),
dict(id='iron_bark', name='Iron Bark', cost=1, el='Nature', cat='Skill', tgt='Self', text='Gain 3 Sharp and 2 Regen.', shape='enabler', cur='Sharp', status='keep'),
dict(id='shrug_off', name='Shrug Off', cost=0, el='Nature', cat='Skill', tgt='Self', text='Remove 1 Weakened, then gain 2 Sharp.', shape='enabler', cur='Sharp', status='keep'),
dict(id='thorn_whip', name='Thorn Whip', cost=1, el='Nature', cat='Attack', tgt='Single', text='15 power. +5 power per Sharp you hold.', shape='scalar', cur='Sharp', status='keep'),
dict(id='pollen_cloud', name='Pollen Cloud', cost=0, el='Nature', cat='Status', tgt='Side', text='Apply 1 Weakened to each enemy.', shape='enabler', cur='Weakened', status='revise', why='Poison removed; 09-23 one-job rule: Snarl is 2 Weakened on one target, Pollen Cloud is 1 on the side.'),
dict(id='heckle', name='Heckle', cost=0, el='Nature', cat='Status', tgt='Single', text='Apply 1 Dazed and 1 Weakened.', shape='enabler', cur='Dazed', status='new'),
dict(id='nagging_bite', name='Nagging Bite', cost=1, el='Nature', cat='Attack', tgt='Single', text='15 power. +20 power if the target is Dazed.', shape='scalar', cur='Dazed', status='keep', why='Binary rider ("is it Dazed?") — Rat’s shape; Kraken’s is per stack.'),
dict(id='pile_on', name='Pile On', cost=2, el='Nature', cat='Attack', tgt='Single', text='45 power. If the target is Dazed, hit again.', shape='scalar', cur='Dazed', status='new'),
dict(id='crippling_vine', name='Crippling Vine', cost=2, el='Nature', cat='Attack', tgt='Side', text='20 power to the enemy side. Apply 2 Weakened to each.', shape='enabler', cur='Weakened', status='revise', why='Was a 1e card with more damage (09-23). Now a SIDE card — a thing two Thorn Tithes cannot do.'),
dict(id='thorn_tithe', name='Thorn Tithe', cost=1, el='Nature', cat='Attack', tgt='Single', text='30 power. Apply 3 Weakened.', shape='enabler', cur='Weakened', status='keep'),
dict(id='sap_strength', name='Sap Strength', cost=1, el='Nature', cat='Attack', tgt='Single', text='20 power. +6 power per Weakened on the target.', shape='scalar', cur='Weakened', status='new', why='The Weakened scalar; reads the TARGET, so Kraken’s or Rat’s Weakened counts.'),
dict(id='hexbloom', name='Hexbloom', cost=2, el='Nature', cat='Status', tgt='Single', text='Apply 1 Poison per Weakened on the target, then remove the Weakened.', shape='consume', cur='Weakened', status='keep'),
dict(id='heartwood', name='Heartwood', cost=1, el='Nature', cat='Status', tgt='Self', text='Gain 6 Bark Shield. Apply 1 Poison to the target.', shape='enabler', cur='Bark', status='keep'),
dict(id='shell_share', name='Shell Share', cost=1, el='Nature', cat='Skill', tgt='Ally', text='An ally gains 6 Bark Shield.', shape='enabler', cur='Bark', status='new', why='Huldra v2 shields allies by card, not only by OS.'),
dict(id='bark_lash', name='Bark Lash', cost=0, el='Nature', cat='Attack', tgt='Single', text='1 power per point of Bark Shield you hold.', shape='scalar', cur='Bark', status='keep'),
dict(id='bark_smash', name='Bark Smash', cost=2, el='Nature', cat='Attack', tgt='Single', text='Consume your Bark Shield: 6 power per point consumed.', shape='consume', cur='Bark', status='new', why="Henry's 'bark smash'."),
dict(id='thornguard', name='Thornguard', cost=1, el='Nature', cat='Attack', tgt='Single', text='20 power. Apply 3 Poison if you are shielded.', shape='converter', cur='Poison', status='keep'),
dict(id='blightbloom', name='Blightbloom', cost=2, el='Nature', cat='Attack', tgt='Single', text='30 power. Apply 5 Poison.', shape='enabler', cur='Poison', status='keep'),
dict(id='nettle_sting', name='Nettle Sting', cost=1, el='Nature', cat='Attack', tgt='Single', text='22 power. Apply 1 Poison.', shape='enabler', cur='Poison', status='keep', why='Huldra v2 only. TRIED AND REVERTED 2026-09-25: swapped into Ratatoskr v1 for tend as a 1e Nature poison card, measured at 200 seeds, and it cost v1 six points of fight one (91.5 -> 85.5) while the 8.9-turn stall did not move at all - same turns, same 15 of 200 at the turn cap. Rat was winning those fights on GOSSIP_NODE sustain at 72% end HP, not losing them for want of damage; tend was load-bearing and a 1e card earns no proc. Recorded so the swap is not proposed a second time.'),
]

# ---------------- the twelve ----------------
# lanes: A / B; each kit card: (id, copies, lane, start) — start = in the 5-card start kit (161: no consume in the start kit)
# TICKET 158-r1 (Henry, 158 §5.3) — `cur`, `tempo` and `partners` ARE NOT HERE ANY MORE.
# They moved into the registry, `src/engine/data/osGrammar.ts`, so that 157's walker, the recruit
# readout and this browser read one source instead of three copies of a design record. `npm run
# decks` writes them into `registry.json` and `registry_source.apply` sets them on these dicts at
# build time. Everything else about an OS — `ally`, the two lanes, the kit, the pool, the builds
# — is still design-only and still lives here.
OS = [
dict(sp='Fenrir', el='Fire', id='fenrir_v1', os='UNBOUND_KERNEL', text='Attack programs apply 2 Strength and deal 2% max-HP recoil. Allies’ attacks apply 1 Strength to Fenrir. Fire attacks deal more the more HP Fenrir is missing.',
     ally='reads allies’ attacks',
     laneA=('Str consume', 'Stack Strength across bodies, spend it all at once.'), laneB=('Berserker', 'HP is the resource; the lower Fenrir is, the harder Fire hits.'),
     kit=[('war_pact',2,'A',1),('desperate_strike',1,'A',1),('unbound_fang',1,'A',0),('ragnarok_edge',2,'B',1),('glass_cannon',1,'B',1),('forage',1,'G',1)],
     pool=['sun_devourer','fury_strike','blood_rite','flare_burst','core_overclock','howl'],
     builds=[('Str consume','war_pact war_pact desperate_strike fury_strike unbound_fang sun_devourer glass_cannon forage'),('Berserker','ragnarok_edge ragnarok_edge glass_cannon glass_cannon desperate_strike blood_rite war_pact forage'),('With Sköll v1','war_pact war_pact ragnarok_edge glass_cannon sun_devourer unbound_fang howl forage')]),
dict(sp='Fenrir', el='Fire', id='fenrir_v2', os='CINDER_WALL', text='Whenever an ally applies Burn to any unit — including themselves — Fenrir gains 1 Sharp.',
     ally='reads any ally’s Burn',
     laneA=('Cinder ramp', 'Cheap Burns become Sharp; Sharp becomes a lance or a consume.'), laneB=('Burn control', 'Burn the whole side and let the clock run; daemons punish attackers.'),
     kit=[('ignite',2,'A',2),('ember_jab',1,'A',1),('slag_strike',1,'A',1),('cinder_lance',1,'A',1),('sharp_edge',1,'A',0),('flashover',1,'B',0),('forage',1,'G',0)],
     pool=['inferno','molten_core','ember_ward','cinder_armor','ash_communion','heat_wave'],
     builds=[('Cinder ramp','ignite ignite ember_jab slag_strike cinder_lance sharp_edge molten_core forage'),('Burn control','ignite ignite inferno inferno molten_core flashover ember_ward forage'),('With Kraken v2','ignite ember_jab slag_strike cinder_lance sharp_edge inferno molten_core forage')]),
dict(sp='Sköll', el='Fire', id='skoll_v1', os='TREACHERY_KERNEL', text='Whenever an ally loses HP to an enemy, Sköll gains 1 Strength.',
     ally='fed by allies being hit; Howl gives Str back',
     laneA=('Flurry', 'Strength is added per hit — many small hits, each one bigger.'), laneB=('Pack leader', 'Keep the chip damage small, hand the Strength around.'),
     # TICKET 157-r1(b) (Henry, 2026-09-24): ONE payoff in the opening five. This kit had FOUR
     # (flare_burst x2, brute_force, snap). The startCopies column moves; the DECK is unchanged.
     kit=[('fury_strike',2,'A',2),('flare_burst',2,'A',1),('brute_force',1,'A',0),('snap',1,'B',0),('howl',1,'B',1),('forage',1,'G',1)],
     pool=['pack_tactics','snarl','battle_rhythm','reactive_plating','core_overclock','crimson_draw'],
     builds=[('Flurry','fury_strike fury_strike flare_burst flare_burst pack_tactics brute_force battle_rhythm forage'),('Pack leader','snarl snarl snap snap howl howl brute_force forage'),('With Fenrir v1','fury_strike flare_burst flare_burst brute_force howl howl snap forage')]),
dict(sp='Sköll', el='Fire', id='skoll_v2', os='EMBER_FUSE (new)', text='Each of Sköll’s hits on a Burning target applies 1 more Burn — so a three-hit card pays three times. (Burn is permanent, caps at 4, and detonates past the cap.)',
     ally='every ally’s Burn is a fuse Sköll can light',
     laneA=('Detonator', 'Get a pile to 3–4, then Heat Wave or one more hit sets it off.'), laneB=('Kindling', 'Many 0e Burn riders; a scalar that reads the pile.'),
     kit=[('ember_jab',2,'B',2),('brand',2,'A',1),('ignite',1,'B',1),('flashover',1,'B',1),('heat_wave',1,'A',0),('pack_tactics',1,'A',0),('forage',1,'G',0)],
     pool=['wildfire','inferno','thermal_overload','scald','ash_communion','cinder_armor'],
     builds=[('Detonator','brand brand ember_jab ignite heat_wave heat_wave pack_tactics forage'),('Kindling','ember_jab ember_jab ignite ignite brand flashover flashover forage'),('With Kraken v2','brand brand ember_jab heat_wave flashover inferno ignite forage')]),
dict(sp='Ratatoskr', el='Nature', id='ratatoskr_v1', os='GOSSIP_NODE', text='Whenever an ally plays a 0-cost program, that ally heals 2.5% of their max HP.',
     ally='heals whichever ally casts 0e',
     laneA=('Chatter', 'Cast many 0e cards, cash them with Seed Bomb.'), laneB=('Den mother', 'The zoo heals itself; tend the others.'),
     kit=[('acorn_toss',2,'A',2),('forage',2,'A',1),('seed_bomb',1,'A',1),('tend',1,'B',1),('shrug_off',1,'B',0),('thorn_whip',1,'B',0)],
     pool=['echo_chamber','hoofbeat','rejuvenation','mend','verdant_ward','deep_scan'],
     builds=[('Chatter','acorn_toss acorn_toss forage forage tackle seed_bomb seed_bomb echo_chamber'),('Den mother','acorn_toss forage tend tend shrug_off thorn_whip rejuvenation mend'),('With Jorm v1','acorn_toss acorn_toss forage forage seed_bomb hoofbeat tend echo_chamber')]),
dict(sp='Ratatoskr', el='Nature', id='ratatoskr_v2', os='INSTIGATOR', text='Whenever an ally plays a 0-cost card at an enemy, apply 1 Dazed to the target.',
     ally='Dazes the target of any ally’s 0e card',
     laneA=('Heckler', 'Is it Dazed? Then every bite is a big bite.'), laneB=('Nuisance', 'Weakened riders; Hexbloom cashes the pile.'),
     kit=[('acorn_toss',2,'A',2),('heckle',1,'A',1),('nagging_bite',2,'A',1),('pollen_cloud',1,'B',1),('sap_strength',1,'B',0),('forage',1,'G',0)],
     pool=['pile_on','hexbloom','thorn_tithe','echo_chamber','crippling_vine','snarl'],
     builds=[('Heckler','acorn_toss acorn_toss heckle heckle nagging_bite nagging_bite pile_on forage'),('Nuisance','pollen_cloud pollen_cloud heckle crippling_vine sap_strength hexbloom acorn_toss forage'),('With Kraken v1','acorn_toss acorn_toss heckle heckle nagging_bite nagging_bite pile_on tackle')]),
dict(sp='Jörmungandr', el='Water', id='jormungandr_v1', os='OUROBOROS_LOOP', text='Each turn, the 5th Water card your side plays draws 1 card.',
     ally='counts the whole side’s Water cards',
     laneA=('Coil', 'Cheap Water cards, then Serpent’s Coil counts them.'), laneB=('Undertow ramp', 'Draws refund Energy; the fifth card draws again.'),
     kit=[('undertow',2,'A',1),('blind_spot',1,'A',1),('serpents_coil',2,'A',1),('surge_protection',1,'B',1),('riptide_run',1,'B',1),('tackle',1,'G',0)],
     pool=['corrosive_leak','scavenge_data','feedback_loop','hydro_blast','tide_pool','tidal_battery'],
     builds=[('Coil','undertow undertow blind_spot blind_spot serpents_coil serpents_coil scavenge_data tackle'),('Undertow ramp','undertow undertow riptide_run riptide_run surge_protection tide_pool hydro_blast tackle'),('With Kraken v1','undertow undertow blind_spot serpents_coil serpents_coil riptide_run feedback_loop tackle')]),
dict(sp='Jörmungandr', el='Water', id='jormungandr_v2', os='TOXIN_FANG', text='Jörmungandr’s attacks deal +10 damage per Poison stack on the target.',
     ally='reads the TARGET — anyone’s Poison',
     laneA=('Fangs', 'Poison the target, then hit it three times.'), laneB=('Venom pile', 'Contagion doubles the pile; Toxic Surge or Venom Glut cashes it.'),
     kit=[('corrosive_bolt',2,'A',2),('venom_fang',1,'A',1),('serpent_flurry',2,'A',1),('serpents_coil',1,'A',0),('toxic_surge',1,'B',0),('tackle',1,'G',1)],
     pool=['venom_glut','contagion','spreading_rot','blightbloom','nettle_sting','riptide'],
     builds=[('Fangs','corrosive_bolt corrosive_bolt venom_fang serpent_flurry serpent_flurry serpents_coil spreading_rot tackle'),('Venom pile','corrosive_bolt corrosive_bolt contagion contagion toxic_surge venom_glut serpent_flurry tackle'),('With Huldra v2','corrosive_bolt serpent_flurry serpent_flurry venom_fang contagion venom_glut spreading_rot tackle')]),
dict(sp='Kraken', el='Water', id='kraken_v1', os='ABYSSAL_INK_SYS', text='Whenever Kraken’s side draws a card outside the draw phase, apply 2 Dazed to a random enemy.',
     ally='any ally’s draw Dazes for free',
     laneA=('Ink', 'Draw off-phase, Ink Stream counts the draws.'), laneB=('Depths', 'Stack Dazed, consume it per stack.'),
     kit=[('whirlpool',2,'A',2),('undertow',1,'A',1),('ink_stream',2,'A',1),('pressure_point',1,'B',1),('crushing_depths',1,'B',0),('slander',1,'B',0)],
     pool=['ink_cloud','scavenge_data','short_circuit','feedback_loop','deep_scan','static_ward'],
     builds=[('Ink','whirlpool whirlpool undertow scavenge_data ink_stream ink_stream pressure_point feedback_loop'),('Depths','whirlpool whirlpool ink_cloud pressure_point crushing_depths crushing_depths slander undertow'),('With Rat v2','whirlpool whirlpool undertow ink_stream crushing_depths slander pressure_point short_circuit')]),
dict(sp='Kraken', el='Water', id='kraken_v2', os='TIDAL_CRUSH_OS', text='Water cards that cost 2 or more Energy deal 30% more damage.',
     ally='Tidal Battery (run card) ramps the side',
     laneA=('Deep charge', 'Bank Energy for two turns, then Hydro Blast.'), laneB=('Steam', 'Water Burns: a clock that ignores Sharp, and fuel for Fire partners.'),
     kit=[('capacitor',2,'A',1),('tide_pool',1,'A',1),('boiling_surge',2,'B',1),('scald',1,'B',1),('hydro_blast',1,'A',0),('tackle',1,'G',1)],
     pool=['maelstrom','tidal_wave','overclock_core','tidal_battery','ink_cloud','heat_wave'],
     builds=[('Deep charge','capacitor capacitor tide_pool overclock_core hydro_blast maelstrom tidal_wave tackle'),('Steam','scald scald boiling_surge boiling_surge tide_pool heat_wave capacitor tackle'),('With Fenrir v2','capacitor scald scald boiling_surge boiling_surge hydro_blast tide_pool tackle')]),
dict(sp='Huldra', el='Nature', id='huldra_v1', os='ALLURE_PROXY', text='Whenever an ally applies a buff to an ally, Huldra mirrors it: 1 Weakened on a random enemy.',
     ally='buffs allies; every buff Weakens an enemy',
     laneA=('Thorns', 'Weaken them, then read the Weakened.'), laneB=('Keeper', 'Buff the party; the Weakened comes free.'),
     kit=[('bolster',2,'B',2),('tend',1,'B',1),('thorn_tithe',1,'A',1),('sap_strength',1,'A',1),('hexbloom',1,'A',0),('thorn_whip',1,'B',0),('soothe',1,'G',0)],
     pool=['verdant_ward','iron_bark','crippling_vine','mend','static_ward','pollen_cloud'],
     builds=[('Thorns','thorn_tithe thorn_tithe sap_strength sap_strength hexbloom bolster tend soothe'),('Keeper','bolster bolster tend tend verdant_ward mend thorn_whip soothe'),('With Fenrir v1','bolster bolster tend sap_strength thorn_tithe hexbloom verdant_ward soothe')]),
dict(sp='Huldra', el='Nature', id='huldra_v2', os='BARK_SHIELD_OS', text='At the end of Huldra’s first turn she raises a massive Bark Shield, and a smaller one around each ally.',
     ally='shields every ally',
     laneA=('Bark smash', 'Build the shield, then swing it.'), laneB=('Thorn wall', 'Shielded bodies poison what hits them.'),
     kit=[('heartwood',2,'A',2),('bark_lash',2,'A',1),('shell_share',1,'B',1),('thornguard',1,'B',1),('bark_smash',1,'A',0),('tackle',1,'G',0)],
     pool=['blightbloom','nettle_sting','reactive_plating','verdant_ward','mend','iron_bark'],
     builds=[('Bark smash','heartwood heartwood bark_lash bark_lash shell_share bark_smash bark_smash tackle'),('Thorn wall','heartwood heartwood shell_share shell_share thornguard thornguard blightbloom tackle'),('With Jorm v2','heartwood heartwood thornguard thornguard shell_share bark_lash blightbloom tackle')]),
]

RUN_ONLY = ['tidal_battery','overclock_core','short_fuse','riptide','short_circuit','static_ward']  # never in a kit; found in the run
