/**
 * TICKET 200b - `npm run icons`: copies ONLY the Tabler icons the game uses out of the pinned
 * `@tabler/icons` package into `src/ui/theme/tabler.generated.ts`.
 *
 * Offline by design: the desktop build fetches nothing, and there is no icon font. The icons are
 * data in the bundle. Nothing is drawn or edited here; the nodes are Tabler's own (MIT, Paweł Kuna).
 *
 *   npm run icons             write the file
 *   npm run icons -- --check  exit 1 if the file on disk is not what the names would generate
 *
 * Plain Node, no shell, so it runs the same under PowerShell and Git Bash. Output is deterministic
 * (sorted names, sorted attributes, fixed formatting): running it twice gives identical bytes.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PACKAGE = resolve(ROOT, 'node_modules/@tabler/icons');
const NAMES = resolve(ROOT, 'scripts/tabler-icons.names.json');
const PINNED = '3.49.0';
export const OUTPUT = resolve(ROOT, 'src/ui/theme/tabler.generated.ts');

const HEADER = `/**
 * GENERATED by scripts/tabler-icons.mjs (\`npm run icons\`). DO NOT EDIT.
 *
 * Tabler Icons, MIT licence, Paweł Kuna. Only the icons listed in scripts/tabler-icons.names.json.
 * Each icon is its node list exactly as Tabler ships it (a 24 grid, stroke only). Outline and filled
 * sets are kept apart because both have a \`flame\`.
 */

import type { TablerNodes } from './tablerNodes';
`;

const readJson = (file) => JSON.parse(readFileSync(file, 'utf8'));

/** The names file, the package's two node files and its version, read from disk. */
export function readSources() {
    return {
        names: readJson(NAMES),
        outline: readJson(resolve(PACKAGE, 'tabler-nodes-outline.json')),
        filled: readJson(resolve(PACKAGE, 'tabler-nodes-filled.json')),
        version: readJson(resolve(PACKAGE, 'package.json')).version,
    };
}

const quote = (text) => `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const key = (name) => (/^[a-z_][a-z0-9_]*$/i.test(name) ? name : quote(name));

function renderNode([tag, attrs]) {
    const pairs = Object.keys(attrs).sort().map((k) => `${key(k)}: ${quote(String(attrs[k]))}`);
    return `        [${quote(tag)}, { ${pairs.join(', ')} }],`;
}

function renderSet(constName, kind, wanted, available) {
    const lines = [];
    for (const name of [...new Set(wanted)].sort()) {
        const nodes = available[name];
        if (nodes === undefined) {
            throw new Error(`Tabler icon "${name}" (${kind}) does not exist in the installed @tabler/icons.`);
        }
        lines.push(`    ${key(name)}: [`, ...nodes.map(renderNode), '    ],');
    }
    return [`export const ${constName} = {`, ...lines, '} as const satisfies Readonly<Record<string, TablerNodes>>;'].join('\n');
}

/** The full text of `tabler.generated.ts` for these sources. Throws, naming the icon, if one is missing. */
export function generate({ names, outline, filled }) {
    return `${HEADER}
${renderSet('TABLER_OUTLINE', 'outline', names.outline, outline)}

${renderSet('TABLER_FILLED', 'filled', names.filled, filled)}

export type TablerOutlineName = keyof typeof TABLER_OUTLINE;
export type TablerFilledName = keyof typeof TABLER_FILLED;
`;
}

function main() {
    const sources = readSources();
    if (sources.version !== PINNED) {
        throw new Error(`@tabler/icons is ${sources.version}; this repo pins ${PINNED}. Run npm install.`);
    }
    const text = generate(sources);
    if (process.argv.includes('--check')) {
        let onDisk = '';
        try { onDisk = readFileSync(OUTPUT, 'utf8'); } catch { /* a missing file counts as stale */ }
        // .gitattributes checks text out as CRLF on Windows; the repo's copy is LF. Same text either way.
        if (onDisk.replace(/\r\n/g, '\n') !== text) {
            console.error('src/ui/theme/tabler.generated.ts is stale. Run: npm run icons');
            process.exit(1);
        }
        console.log('tabler.generated.ts is up to date.');
        return;
    }
    writeFileSync(OUTPUT, text);
    console.log(`Wrote src/ui/theme/tabler.generated.ts (${sources.names.outline.length} outline, ${sources.names.filled.length} filled).`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    try { main(); } catch (error) { console.error(error.message); process.exit(1); }
}
