/**
 * TICKET 177d — THE REPORT, IN PLAIN ENGLISH, FROM THE MEASURED NUMBERS.
 *
 * `renderCheapAiReport` is a pure function from results to markdown, so the layout can be tested
 * without running a single fight. It ends, as the balance reports do, with numbered decisions.
 */

import { weightsTable } from '../../../engine/ai/cheap/weights';
import type { CheapWeights } from '../../../engine/ai/cheap/weightsSchema';
import { pct, pctInterval } from './cheapAiStats';
import {
    ARMS, SIZE_CLASSES, agreementTable, diagnostics, pairedDifference, speedTable, strengthTable, verdict,
    type MeasureSizes, type ReplayUnit, type StrengthGame, type Tier,
} from './cheapAiMeasure';

export interface ReportInput {
    readonly games: ReadonlyArray<StrengthGame>;
    readonly replay: ReadonlyArray<ReplayUnit>;
    readonly weights: CheapWeights;
    readonly weightsSource: string;
    readonly sizes: MeasureSizes;
    /** How many fights the teacher recording holds when the report was written. */
    readonly teacherFights: number;
    readonly generatedBy: string;
}

const TIER_LABEL: Record<Tier, string> = {
    cheap: 'cheap (weighted features)',
    lite: 'lite (narrowed lookahead)',
    greedy: 'greedy (no lookahead)',
    full: 'full (the shipped AI)',
};

const ms = (x: number): string => (x >= 100 ? x.toFixed(0) : x >= 10 ? x.toFixed(1) : x.toFixed(2));

/** Which feature to add next, and why, read off where the cheap AI disagrees with the teacher. */
function nextFeature(d: ReturnType<typeof diagnostics>): string[] {
    if (d.disagreements === 0) return ['There were no disagreements to learn from.'];
    const total = d.disagreements;
    const ends = d.cheapEndsTeacherPlays;
    const plays = d.cheapPlaysTeacherEnds;
    const other = d.bothPlayDifferently;
    const share = (n: number): string => pct(n / total, 0);
    const lines: string[] = [
        `Of ${total} decisions where cheap disagreed with the full AI: cheap stopped when the full AI kept playing ${share(ends)}, `
        + `cheap kept playing when the full AI stopped ${share(plays)}, and both played but chose different actions ${share(other)}.`,
    ];
    const top = d.gaps.slice(0, 3).map((g) => `${g.feature} (the teacher's pick had ${g.meanGap >= 0 ? 'more' : 'less'} of it)`).join(', ');
    lines.push(`The features the teacher's choice differed from cheap's on most, in order: ${top}.`);
    if (other >= ends && other >= plays) {
        lines.push(
            'The biggest block is two plays that both look fine one move deep. What the full AI sees that a one-move policy cannot is the '
            + 'REST OF THE TURN: what the remaining hand can still do with the energy left after this play. The feature I would add next '
            + 'is `handPotential`: the best damage (and kills) the cards still in hand could add this turn from the position after the '
            + 'play, one reducer call per remaining card. It is the cheapest way to give a one-move policy a view of sequencing.',
        );
    } else if (ends >= plays) {
        lines.push(
            'The biggest block is cheap stopping early. The feature I would add next is `playableLeft`: how many cards in hand can still be '
            + 'afforded and legally cast after this action. `energyLeft` alone cannot tell "energy left and nothing to spend it on" from '
            + '"energy left and a good card waiting".',
        );
    } else {
        lines.push(
            'The biggest block is cheap playing on when the full AI stops. The feature I would add next is `exposureAfter`: the damage the '
            + 'opponent\'s side could still deal next turn after this action, so that spending the turn on a weak play that leaves the '
            + 'party exposed prices in its cost.',
        );
    }
    return lines;
}

export function renderCheapAiReport(input: ReportInput): string {
    const strength = strengthTable(input.games);
    const agreement = agreementTable(input.replay);
    const speed = speedTable(input.replay);
    const v = verdict(strength, speed);
    const diff = pairedDifference(input.games, 'cheap', 'lite');
    const diag = diagnostics(input.replay);
    const L: string[] = [];

    L.push('# Ticket 177: how good is the cheap AI?');
    L.push('');
    L.push(`**${v.line}**`);
    L.push('');
    L.push(`Generated by \`${input.generatedBy}\`. The cheap AI plays by the weights in \`src/engine/ai/cheap/weights.json\` (${input.weightsSource}). `
        + `The teacher recording held ${input.teacherFights} fights when this was written.`);
    L.push('');
    L.push('## What was measured');
    L.push('');
    L.push('The cheap AI is a list of named features with a weight each. For every legal action it simulates the action once, adds up '
        + 'weight times feature, and plays the best one. It was fitted to copy the full AI (the shipped search AI) from a recording of '
        + 'the full AI playing itself. The bar from the ticket (C2) is two things at once: its win rate against the full AI is at least '
        + 'the `lite` tier\'s win rate against the full AI on the same games, and it is at least 10 times faster per decision than `lite`. '
        + 'Nothing was tuned toward the bar. If it is missed, it is reported as missed.');
    L.push('');
    L.push('"Class-averaged" below means the 1v1, 2v2 and 3v3 win rates are averaged with equal weight, because most games are 1v1 and a '
        + 'pooled number would be a 1v1 number. "10 times faster" has to hold at both 1v1 and 3v3.');
    L.push('');

    L.push('## 1. Agreement with the full AI');
    L.push('');
    L.push('Fights the fit never saw (held out by fight) were replayed move by move using the full AI\'s own choices, and at every position '
        + 'each tier was asked what it would play. The number is how often it named the same action. The full AI must read 100% '
        + '(it is the teacher), which also proves the replay is faithful.');
    L.push('');
    L.push('| tier | ' + [...SIZE_CLASSES, 'all'].map((c) => c === 'all' ? 'all decisions' : c).join(' | ') + ' |');
    L.push('|---|' + [...SIZE_CLASSES, 'all'].map(() => '---').join('|') + '|');
    for (const tier of ARMS) {
        const cells = [...SIZE_CLASSES, 'all' as const].map((cls) => {
            const row = agreement.find((r) => r.tier === tier && r.cls === cls);
            return row ? `${pctInterval(row.rate)}, n=${row.decisions}` : '—';
        });
        L.push(`| ${TIER_LABEL[tier]} | ${cells.join(' | ')} |`);
    }
    L.push('');

    L.push('## 2. Strength against the full AI');
    L.push('');
    L.push('Each tier plays the player side against the full AI on the enemy side, on the matchups from the recording with fresh seeds, '
        + `both sides moving first, the same games for every tier (${input.sizes.seeds1v1} seeds per 1v1 matchup over all 132 ordered pairs, `
        + `${input.sizes.matchups2v2} 2v2 matchups x ${input.sizes.seeds2v2}, ${input.sizes.matchups3v3} 3v3 matchups x ${input.sizes.seeds3v3}). `
        + 'A win is a point and a draw half a point. The intervals are 95%. The full-against-full row is the baseline: it is not 50% for '
        + '2v2 and 3v3 because those matchups are one-directional (the player side holds a fixed team), so read every row against it.');
    L.push('');
    L.push('| tier | ' + [...SIZE_CLASSES, 'class-averaged'].join(' | ') + ' |');
    L.push('|---|' + [...SIZE_CLASSES, 'x'].map(() => '---').join('|') + '|');
    for (const arm of ARMS) {
        const cells = [...SIZE_CLASSES, 'all' as const].map((cls) => {
            const row = strength.find((r) => r.arm === arm && r.cls === cls);
            return row ? `${pctInterval(row.rate)}, ${row.games} games` : '—';
        });
        L.push(`| ${TIER_LABEL[arm]} | ${cells.join(' | ')} |`);
    }
    L.push('');
    L.push('Cheap minus lite on the very same games (paired, so the dice cancel):');
    L.push('');
    L.push('| fight size | cheap minus lite | 95% interval | games |');
    L.push('|---|---|---|---|');
    for (const row of diff) {
        L.push(`| ${row.cls === 'all' ? 'class-averaged' : row.cls} | ${(100 * row.diff.estimate).toFixed(1)} points | `
            + `${(100 * row.diff.lo).toFixed(1)} to ${(100 * row.diff.hi).toFixed(1)} | ${row.diff.n} |`);
    }
    L.push('');

    L.push('## 3. Speed');
    L.push('');
    L.push('Milliseconds per decision, the same positions for every tier, one decision at a time, with the machine otherwise idle. '
        + 'Mean and 95th percentile.');
    L.push('');
    L.push('| tier | ' + SIZE_CLASSES.map((c) => `${c} mean / p95`).join(' | ') + ' |');
    L.push('|---|' + SIZE_CLASSES.map(() => '---').join('|') + '|');
    for (const tier of ARMS) {
        const cells = SIZE_CLASSES.map((cls) => {
            const row = speed.find((r) => r.tier === tier && r.cls === cls);
            return row ? `${ms(row.timing.mean)} / ${ms(row.timing.p95)} ms (n=${row.timing.n})` : '—';
        });
        L.push(`| ${TIER_LABEL[tier]} | ${cells.join(' | ')} |`);
    }
    L.push('');
    const x = (n: number | undefined): string => (n === undefined ? 'n/a' : `${n.toFixed(1)} times`);
    L.push(`Cheap is ${x(v.speedup['1v1'])} faster than lite at 1v1 and ${x(v.speedup['3v3'])} faster at 3v3 (mean per decision).`);
    L.push('');

    L.push('## 4. Verdict');
    L.push('');
    L.push(`**${v.line}**`);
    L.push('');
    L.push('The two numbers the strength half compares: '
        + `cheap ${(100 * v.cheapRate).toFixed(1)}% against lite ${(100 * v.liteRate).toFixed(1)}% (class-averaged win rate against the full AI). `
        + 'The two the speed half compares: lite\'s mean milliseconds per decision divided by cheap\'s, at 1v1 and at 3v3, against 10.');
    L.push('');

    L.push('## 5. The weights it played with');
    L.push('');
    L.push('```');
    L.push(weightsTable(input.weights));
    L.push('```');
    L.push('');

    if (!v.met) {
        L.push('## 6. If it missed: what I would add next');
        L.push('');
        for (const line of nextFeature(diag)) { L.push(line); L.push(''); }
        L.push('This is a suggestion from where the disagreements are, not something tried. Nothing in this report was tuned toward the bar.');
        L.push('');
    }

    L.push('## Decisions and next steps');
    L.push('');
    L.push(v.met
        ? '1. The cheap AI meets the bar as defined above. Whether it replaces `lite` in the long balance jobs (the walker, the tier ladder, '
        + 'the deck search) is yours to rule; it is selectable now as `playerAiTier` / `enemyAiTier` = `cheap`.'
        : '1. The cheap AI misses the bar as defined above. It stays an option for simulations (`playerAiTier` / `enemyAiTier` = `cheap`) and '
        + 'nothing in the shipped game or the existing balance runs uses it. Say whether to try the next feature.');
    L.push('2. Shipped enemies do not use it (C3). Whether wild enemies should is a later ruling, and these are the numbers to make it from.');
    L.push('3. The weights are a fit to a recording of the full AI. Re-record and re-fit whenever the full AI\'s evaluation changes '
        + '(`runRecordTeacher.ts`, then `runFitWeights.ts`), then re-run this measurement.');
    L.push('');
    return L.join('\n');
}
