/**
 * THE DECK BROWSER — a reference card for the twelve tuned decks, built for reading rather than
 * for analysis.
 *
 * Henry, 2026-08-27: *"I need a tool to look at the current decks. A way to scroll through the
 * different mingmings and their tuned decks so I can compare. I always forget the current decks and
 * what each OS is… easy to read at a glance, not JSON, interactive."*
 *
 * # WHY THIS IS NOT `deckReport.ts`
 *
 * `npm run balance:deck` already produces a viewer, and it is a good one — matchup grids, redlines,
 * per-card telemetry, 456 KB of it. It answers *"is this deck balanced"*. This answers a different
 * question that the same data cannot: **"what IS this deck, and what does its firmware do?"** The
 * two want opposite shapes. A balance report is a table you scan for outliers; a reference is a page
 * you read one deck at a time, and the thing that has to be biggest on it is the OS description and
 * the five cards that make the engine.
 *
 * So this reads the **live registry** for everything structural and *borrows* the balance numbers,
 * rather than the other way round.
 *
 * # THE DECK DATA IS ALWAYS CURRENT. THE STATS MAY NOT BE. THAT DISTINCTION IS THE FEATURE.
 *
 * Henry: *"Mark it stale if we have made changes that affect it."*
 *
 * Every deck list, card text, cost, OS description and engine tag on this page is read out of
 * `MingmingRegistry` / `ProgramRegistry` **at generation time**, so re-running the command is all it
 * takes to be current. The win rates cannot work that way — they cost hours of simulation — so they
 * are joined in from `docs/balance/deck_report.json` and stamped with the registry hash they were
 * measured against.
 *
 * `computeRegistryHash()` already exists for exactly this purpose (the scenario format uses it to
 * refuse a stale replay), and it hashes the card and species definitions. So the check is honest
 * rather than a heuristic about file dates: **if a card's numbers moved, the hash moved, and every
 * borrowed statistic on the page is marked stale.** At the time of writing it already is — the deck
 * report was taken at `1:ce1ac459` and the registry is at `1:1ad8616b`.
 *
 * A stale number is dimmed and badged rather than hidden. Hiding it would leave the page silently
 * missing a column and send the reader to the JSON; showing it unmarked would be worse than showing
 * nothing at all.
 *
 * # THE TWELVE, AND THE OTHER TWENTY
 *
 * `PLAYABLE_SPECIES` holds sixteen species and `LAUNCH_SPECIES` six of them. Only the launch six
 * carry ratified `startKits` tags and tuned decks; the other ten are reachable but untuned, and
 * `startKitIdsFor` would fall back to "the first five cards of the deck" with a warning. Both are
 * listed — a reference that hid two thirds of the roster would be lying about what the registry
 * holds — but the untuned ones are flagged, sorted last, and carry no engine row, because a tag list
 * nobody chose is not an engine.
 *
 * Debug module: this is generated by hand into `docs/balance/`, ships in no build, and is asserted
 * absent from `dist/` by `scripts/assert-no-debug.mjs` along with the rest of the toolkit.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import {
    LAUNCH_SPECIES,
    MingmingRegistry,
    PLAYABLE_SPECIES,
    getDeckForOS,
} from '../../engine/data/mingmingRegistry';
import { ProgramRegistry } from '../../engine/data/programRegistry';
import { getOSBehavior } from '../../engine/data/firmwareRegistry';
import { numericBaseCost } from '../../engine/types';
import { computeRegistryHash } from '../scenarios/registryHash';

export const DECK_BROWSER_HTML_PATH = 'docs/balance/deck_browser.html';
export const DECK_REPORT_SOURCE_PATH = 'docs/balance/deck_report.json';
const TEMPLATE_PATH = resolve('src/debug/balance/deckBrowserTemplate.html');

/** The highest cost the curve breaks out; anything above lands in the top bucket. */
export const MAX_CURVE_COST = 4;

export interface BrowserCard {
    readonly id: string;
    readonly name: string;
    readonly description: string;
    readonly element: string;
    readonly category: string;
    readonly rarity: string;
    readonly cost: number;
    /** Copies of this card in the tuned deck. The duplicate IS the design — see `startKitIdsFor`. */
    readonly count: number;
    /**
     * `payoff` for the engine's first tag, `enabler` for the other four, absent for everything else.
     * Ticket 61 ratified the five and made position meaningful: the payoff is the card the other
     * four exist to set up.
     */
    readonly engineRole?: 'payoff' | 'enabler';
    /** Borrowed from the deck report, and stale whenever `stats.stale` is true. */
    readonly playRate?: number;
    readonly deadRate?: number;
    readonly avgDamagePerPlay?: number;
}

export interface BrowserDeck {
    readonly id: string;
    readonly species: string;
    readonly speciesName: string;
    readonly element: string;
    readonly secondaryElement?: string;
    /** One of the six launch species, i.e. one of the twelve decks that actually ship. */
    readonly launch: boolean;
    readonly baseStats: Readonly<Record<string, number>>;
    readonly cardDraw: number;
    readonly os: { readonly id: string; readonly name: string; readonly description: string };
    /** The ratified five, payoff first. Empty for an untuned species — see the header. */
    readonly engine: ReadonlyArray<string>;
    readonly cards: ReadonlyArray<BrowserCard>;
    readonly deckSize: number;
    /** Counts by cost, index 0..MAX_CURVE_COST, the last bucket inclusive of everything above. */
    readonly curve: ReadonlyArray<number>;
    readonly archetypeSummary?: string;
    readonly summary?: Readonly<Record<string, unknown>>;
}

export interface BrowserPayload {
    readonly generatedAt: string;
    readonly registryHash: string;
    readonly decks: ReadonlyArray<BrowserDeck>;
    /** Absent when no deck report has ever been generated. */
    readonly stats?: {
        readonly source: string;
        readonly generatedAt: string;
        readonly registryHash: string;
        /** True when the report was measured against a different registry than the one on disk. */
        readonly stale: boolean;
        readonly command?: string;
    };
}

interface DeckReportShape {
    generatedAt?: string;
    registryHash?: string;
    command?: string;
    subjects?: Array<{
        id?: string;
        archetypeSummary?: string;
        summary?: Record<string, unknown>;
    }>;
    cards?: Array<{
        cardId?: string;
        subjectId?: string;
        playRate?: number;
        deadRate?: number;
        avgDirectDamagePerPlay?: number;
    }>;
}

/**
 * Read the deck report, if there is one.
 *
 * A missing or unreadable file is **not an error**: the browser's whole structural half comes from
 * the registry, so a repo that has never run `balance:deck` still gets a complete reference with an
 * empty stats column. Throwing here would make the reference tool depend on an hours-long
 * simulation, which is precisely the coupling this file exists to avoid.
 */
export function readDeckReport(path = DECK_REPORT_SOURCE_PATH): DeckReportShape | null {
    if (!existsSync(path)) return null;
    try {
        return JSON.parse(readFileSync(path, 'utf8')) as DeckReportShape;
    } catch {
        return null;
    }
}

/** One tile's worth of card, before the deck report's telemetry is joined onto it. */
function faceOf(id: string, count: number, engine: ReadonlyArray<string>): BrowserCard {
    const data = ProgramRegistry[id] as
        | {
            name?: string; description?: string; element?: string;
            category?: string; rarity?: string; baseCost?: number | 'X';
        }
        | undefined;
    const engineIndex = engine.indexOf(id);
    return {
        id,
        name: data?.name ?? id,
        description: data?.description ?? '',
        element: data?.element ?? 'None',
        category: data?.category ?? 'Skill',
        rarity: data?.rarity ?? 'Common',
        cost: numericBaseCost(data?.baseCost ?? 0),
        count,
        ...(engineIndex === 0 ? { engineRole: 'payoff' as const }
            : engineIndex > 0 ? { engineRole: 'enabler' as const } : {}),
    };
}

/**
 * Build the whole payload from the live registry, joining the deck report where it lines up.
 *
 * **Joined by OS id and card id, never by position.** The report is a different generation of the
 * game — that is the entire premise of the staleness banner — so a card it measured may have been
 * removed from the deck since, and a card in the deck now may never have been measured. Both cases
 * are ordinary: the first simply does not appear (the deck list is the live one), and the second
 * shows a card with no telemetry, which reads correctly as "this is newer than the numbers".
 */
export function buildBrowserPayload(report: DeckReportShape | null = readDeckReport()): BrowserPayload {
    const registryHash = computeRegistryHash();

    const subjectById = new Map((report?.subjects ?? []).map((s) => [s.id ?? '', s]));
    const cardStats = new Map<string, { playRate?: number; deadRate?: number; avgDamagePerPlay?: number }>();
    for (const card of report?.cards ?? []) {
        if (!card.cardId || !card.subjectId) continue;
        cardStats.set(`${card.subjectId}|${card.cardId}`, {
            playRate: card.playRate,
            deadRate: card.deadRate,
            avgDamagePerPlay: card.avgDirectDamagePerPlay,
        });
    }

    const decks: BrowserDeck[] = [];
    for (const species of PLAYABLE_SPECIES) {
        const definition = MingmingRegistry[species] as
            | {
                name?: string;
                primaryElement?: string;
                secondaryElement?: string;
                baseStats?: Record<string, number>;
                cardDraw?: number;
                availableOS?: string[];
                startKits?: Record<string, string[]>;
            }
            | undefined;
        if (!definition) continue;
        const launch = (LAUNCH_SPECIES as ReadonlyArray<string>).includes(species);

        for (const osId of definition.availableOS ?? []) {
            const engine = launch ? definition.startKits?.[osId] ?? [] : [];

            // The deck carries duplicates on purpose ("one copy is a coin flip and two is an
            // engine"), so the tile keeps a count rather than the list being deduped.
            const counts = new Map<string, number>();
            for (const id of getDeckForOS(species, osId)) counts.set(id, (counts.get(id) ?? 0) + 1);

            const cards = [...counts.entries()]
                .map(([id, count]) => {
                    const face = faceOf(id, count, engine);
                    const stats = cardStats.get(`${osId}|${id}`);
                    return stats ? { ...face, ...stats } : face;
                })
                // Engine first (payoff, then enablers), then by cost, then by name — the order a
                // reader wants, which is not the order the deck happens to be stored in.
                .sort((a, b) => {
                    const rank = (c: BrowserCard) =>
                        c.engineRole === 'payoff' ? 0 : c.engineRole === 'enabler' ? 1 : 2;
                    return rank(a) - rank(b) || a.cost - b.cost || a.name.localeCompare(b.name);
                });

            const curve = Array.from({ length: MAX_CURVE_COST + 1 }, () => 0);
            for (const card of cards) curve[Math.min(card.cost, MAX_CURVE_COST)] += card.count;

            const behaviour = getOSBehavior(osId) as { name?: string; description?: string } | undefined;
            const subject = subjectById.get(osId);

            decks.push({
                id: osId,
                species,
                speciesName: definition.name ?? species,
                element: definition.primaryElement ?? 'None',
                ...(definition.secondaryElement && definition.secondaryElement !== 'None'
                    ? { secondaryElement: definition.secondaryElement } : {}),
                launch,
                baseStats: { ...(definition.baseStats ?? {}) },
                cardDraw: definition.cardDraw ?? 0,
                os: {
                    id: osId,
                    name: behaviour?.name ?? osId,
                    description: behaviour?.description ?? 'No firmware description in the registry.',
                },
                engine: [...engine],
                cards,
                deckSize: cards.reduce((sum, card) => sum + card.count, 0),
                curve,
                ...(subject?.archetypeSummary ? { archetypeSummary: subject.archetypeSummary } : {}),
                ...(subject?.summary ? { summary: subject.summary } : {}),
            });
        }
    }

    // Launch decks first — they are the ones that ship and the ones Henry is comparing — then by
    // element so the type cycle reads down the rail, then by name.
    decks.sort((a, b) =>
        Number(b.launch) - Number(a.launch)
        || a.element.localeCompare(b.element)
        || a.speciesName.localeCompare(b.speciesName)
        || a.id.localeCompare(b.id));

    return {
        generatedAt: new Date().toISOString(),
        registryHash,
        decks,
        ...(report
            ? {
                stats: {
                    source: DECK_REPORT_SOURCE_PATH,
                    generatedAt: report.generatedAt ?? 'unknown',
                    registryHash: report.registryHash ?? 'unknown',
                    stale: report.registryHash !== registryHash,
                    ...(report.command ? { command: report.command } : {}),
                },
            }
            : {}),
    };
}

/**
 * Render the payload into the standalone page.
 *
 * Same mechanism `writeDeckReportViewer` uses, and deliberately: one HTML template with one JSON
 * placeholder, so the page is a file Henry can double-click with no server, no build step and no
 * `npm run dev` — which is the requirement that started this ("not the main game").
 */
export function writeDeckBrowser(payload: BrowserPayload, path = DECK_BROWSER_HTML_PATH): string {
    const template = readFileSync(TEMPLATE_PATH, 'utf8');
    if (!template.includes('__DECK_BROWSER_JSON__')) {
        throw new Error('[deckBrowser] Template is missing its __DECK_BROWSER_JSON__ placeholder.');
    }
    // `</script>` inside the payload would close the host tag early; the JSON spec allows the
    // escape and `JSON.parse` reads it back identically.
    const json = JSON.stringify(payload).replace(/<\/script/gi, '<\\/script');
    if (!existsSync(dirname(path))) mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, template.replace('__DECK_BROWSER_JSON__', json), 'utf8');
    return path;
}
