/**
 * THE REDLINE STAYS TRUE — ticket 162b, Henry 2026-09-23: *"add a list of redlined cards to review
 * later."*
 *
 * `collection-v2/REDLINE.md` is generated by `scratch/t162b_redline.ts` from the live registry
 * through the live scorer, which is what stops it going stale. But a generated file only helps if
 * somebody regenerates it, and the failure is silent: the page keeps naming a card that was fixed
 * and stops naming one that broke.
 *
 * So the suite holds the two claims a reader depends on:
 *
 *  1. **The bands on the page are the bands in the code.** The page states Henry's slot tax in
 *     power; `BUDGET_BANDS` states it in scorer units. A drift between those two is a review list
 *     that measures against a curve nobody is using.
 *  2. **A ruled card is still a card the generator would list.** `RULINGS` records Henry's verdicts
 *     by id, and an id that no longer appears in the collection — renamed, cut — would sit there
 *     forever as a verdict on nothing.
 *
 * Deliberately NOT asserted: the page's contents against a fresh run. That would be a snapshot
 * test over a file whose whole purpose is to change when the registry does, and it would fail on
 * every legitimate card edit — which trains people to regenerate without reading, the exact habit
 * the list exists to interrupt.
 */
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { BUDGET_BANDS, BAND_TOLERANCE_PCT } from './powerscale';
import { getInflatedProgramRegistry } from '../../engine/data/programRegistry';

const REDLINE = path.join('docs', 'wayfinder', 'deck-archetypes', 'collection-v2', 'REDLINE.md');
const GENERATOR = path.join('scratch', 't162b_redline.ts');

describe('the redline list', () => {
    it('exists, and names the script that regenerates it', () => {
        expect(fs.existsSync(REDLINE), `${REDLINE} is missing — run \`npx vite-node ${GENERATOR}\``).toBe(true);
        expect(fs.readFileSync(REDLINE, 'utf8')).toContain('t162b_redline.ts');
    });

    it('quotes the bands the scorer is actually using', () => {
        // The page prints power; BUDGET_BANDS holds scorer units (power/10). Henry's slot tax.
        const page = fs.readFileSync(REDLINE, 'utf8');
        const inPower = BUDGET_BANDS.map((b) => b.over * 10);
        expect(inPower).toEqual([12, 30, 70, 120]);
        expect(page, 'the page states the live band table').toContain(inPower.join(' / '));
        expect(page, 'the page states the live tolerance').toContain(`±${BAND_TOLERANCE_PCT}%`);
    });

    it('records no ruling for a card that has left the registry', () => {
        // A verdict keyed by an id nothing answers to is a verdict on nothing, and it would sit in
        // the generator forever looking authoritative.
        const source = fs.readFileSync(GENERATOR, 'utf8');
        const block = source.slice(source.indexOf('const RULINGS'), source.indexOf('/** Findings that are about a KIT'));
        const ruled = [...block.matchAll(/^\s{4}(\w+):\s*\{\s*verdict/gm)].map((m) => m[1]);
        expect(ruled.length, 'the RULINGS block parsed to nothing — the regex is stale').toBeGreaterThan(0);
        const registry = getInflatedProgramRegistry();
        expect(ruled.filter((id) => !registry[id])).toEqual([]);
    });
});
